### ISSUE TITLE
Missing unit tests

### ISSUE THREAD

**Issue by hx-markterry** [holidayextras/jsonapi-store-mongodb#16]
We need to write some unit tests for this module so new PR's can have their code changes tested by CI and work can follow our best practices.

**Comment by theninj4** [comment]
We already have good coverage over all the core features and functionality, we're just lacking coverage over the real edge-cases (notably any case where an error originates in MongoDB).

https://coveralls.io/builds/4313171/source?filename=lib%2FmongoHandler.js
