### ISSUE TITLE
Can we take control of the resource ID when creating a new resource?

### ISSUE THREAD

**Issue by toddsor** [holidayextras/jsonapi-store-mongodb#18]
When a resource is configured an "id" field is added to the schema atttibutes: see 
jsonapi-server\lib\jsonApi.js:89

This works for the sample data because the data already has an "id" field but mongodb uses "_id".

This brings up a related issue. In the find method in jsonapi-store-mongodb\lib\mongoHandler.js the '_id' field is omitted from the results.

Can the validation be configured to use the native '_id' that mongodb uses?

**Comment by pmcnr-hx** [comment]
Hi @toddsor. I am not exactly sure what is your issue from the above description. Can you please clarify?

**Comment by toddsor** [comment]
Sorry, let me take one thing at a time.

The populate method in mongoHandler.js does validation prior to storing the record. This is ok as long as my app has created a record that includes an 'id' field but I don't want my app to do this, I want mongo to do this for me. 

According to http://jsonapi.org/format/#crud-creating the following should be a valid post:

````
POST /photos HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "photos",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },
    "relationships": {
      "photographer": {
        "data": { "type": "people", "id": "9" }
      }
    }
  }
}
```

Since the 'id' field is missing the validation process returns 'child "id" fails because ["id" is required] ' error. I suggest checking for the 'id' field and if missing then get one from the database. Is it possible to just map the '_id' to 'id'?

**Comment by pmcnr-hx** [comment]
Apologies for the late reply @toddsor. Again I'm still a bit confused. You are using the store with the `jsonapi-server` module right? This should generated the `id` for you if one is not given explicitly.

**Comment by theninj4** [comment]
Hi @toddsor - @pmcnr-hx is correct in saying that `jsonapi-server` (the module these `jsonapi-store-*` modules are intended to be used with) will generate a UUID for us. That said, it's entirely possible for a resource handler to disregard the autogenerated id and create its own. This file: https://github.com/holidayextras/jsonapi-server/blob/master/documentation/suggested-project-structure.md suggests how you can wrap these base CRUD handlers with additional functionality which will provide you with a place where you can control the id.
