### ISSUE TITLE
Has updated the NPM module?

### ISSUE THREAD

**Issue by slonofanya** [holidayextras/jsonapi-store-mongodb#23]
Has updated the [NPM](https://www.npmjs.com/package/jsonapi-store-mongodb) with [fix](https://github.com/holidayextras/jsonapi-store-mongodb/pull/22)?

**Comment by pmcnr-hx** [comment]
We haven't cut a new release yet I am afraid. Can you install from GitHub for now @slonofanya? If not I'll try to do a new release soon.
