### ISSUE TITLE
Question: possible to expand or extend handler with side-effects?

### ISSUE THREAD

**Issue by paul42** [holidayextras/jsonapi-store-mongodb#25]
I noticed in the documentation that there's this snippet of the example:

    handlers: new MongoStore({
    url: "mongodb://localhost:27017/jsonapi",
    })

I was wondering if it's possible to perform actions before or after the call - for example if I wanted to have the end-user call into the api with some information, before storing that, could I make another action (fire an async call to another, remote API) and save? or does this only support CRUD operations? let me know if there is more documentation that I should be reading up on.

Thanks in advance,
Paul

**Comment by paul42** [comment]
am I correct in assuming I can use this format here, listed in the original docs?
https://github.com/holidayextras/jsonapi-server/blob/master/documentation/suggested-project-structure.md
at the very bottom, the commented out area

**Comment by theninj4** [comment]
Hi @paul42 - sorry for the delay. The jsonapi-server `handlers` are shared amongst all requests, and these `jsonapi-store-*` modules are all CRUD. You're correct in that if you want to take the base MongoDB behaviour and also add additional behaviour alongside, you'll be wanting to follow the commented out snipped in the documentation you've linked :+1:
