### ISSUE TITLE
filter and fields don't work

### ISSUE THREAD

**Issue by jbockerstette** [holidayextras/jsonapi-store-mongodb#28]
Basic GET and POST work but passing the filter or fields parameters cause 403 error.

**Comment by pmcnr-hx** [comment]
Hi @jbockerstette can you please supply an example of the request you're making so we can reproduce your issue.

**Comment by jbockerstette** [comment]
curl -X GET --header 'Accept: application/vnd.api+json'
'http://107.170.10.170:16006/1/articles?fields=title

1. Should this just return titles only? It returns all articles and all fields.

http://107.170.10.170:16006/1/articles?filter=title%3D%3D%22NodeJS%20Best%20Practices%22

2. Shouldnt this return only articles with title = "Node JS Best Practices"?

It returns this:

{
  "jsonapi": {
    "version": "1.0"
  },
  "meta": {
    "description": "This block shows up in the root node of every payload"
  },
  "links": {
    "self": "http://localhost:16006/1/articles"
  },
  "errors": [
    {
      "status": "403",
      "code": "EFORBIDDEN",
      "title": "Invalid filter",
      "detail": "articles do not have property 0"
    }
  ]
}

**Comment by jbockerstette** [comment]
Pedro,

Here is the real problem.

If you paste this into the browser it works as expected.
http://107.170.10.170:16006/1/articles?fields[articles]=title

However, if you use swagger.io UI, swagger turns the above statement to
this:
http://107.170.10.170:16006/1/articles?fields=%5Barticles%5D%3Dtitle

swagger encodes the brackets and equals into %5B, %5D and %3D.  It appears
that this encoding is breaking it. Maybe all you need to do is decode it
before processing.

I apologize for poor problem definition previously.

Jim

**Comment by pmcnr-hx** [comment]
Thank you very much for the detective work Jim! I believe you are right and we're not urldecoding the query parameters as we should. I'll close the issue here and open it instead in the [`jsonapi-store`](https://github.com/holidayextras/jsonapi-server) project where it needs to be solved.

**Comment by jbockerstette** [comment]
Agreed.
