### ISSUE TITLE
_id mongo field contains data that java driver cannot parse

### ISSUE THREAD

**Issue by jbockerstette** [holidayextras/jsonapi-store-mongodb#30]
In /lib/mongoHandler.js you will see the line...

```
MongoStore._mongoUuid = function(uuid) {
  return new mongodb.Binary(uuid, mongodb.Binary.SUBTYPE_UUID);
};
```

A POST will result in a new object created with 
`{"_id" : BinData(4,"NmQzMmU2ZDItMTcyYS00YTk3LWFkYzctNTZkZDE1OTEwMGVm")}`

If you try to use the Java driver to read this back, it will throw an exception because it cannot deserialize this. I have not tried other drivers but Java can't handle it.

```
Document rpps = db.getCollection("rpps").find().first();
String str = rpps.toJson(); //  <-------- Throws exception.
System.out.println(str);
```

I would suggest that you use ObjectID() instead of Binary as the Java driver can understand 

`{"_id" : ObjectId("57587cfa92db041ebcc10cf4")}`

Even better is that if the user has already provided a valid uuid as stored in the id field, then just use that id. Maybe you should only create a uuid if none was provided and don't worry about the validitiy, but I am not sure about allowing invalid uuid fields provided by the user. But I would definitely like to see you accept a valid uuid as provided by the POST id field.

**Comment by pmcnr-hx** [comment]
Hi @jbockerstette. The objects serialisation for the `jsonapi-store-mongodb` was designed to be opaque (i.e. only used by the `jsonapi-server`) and we don't recommend it should be manipulated directly.

Having said that, the MongoDB Java driver is supported to properly support _Binary with subtype 0x04_ properties: https://jira.mongodb.org/browse/JAVA-403. Would that solve your issue?

**Comment by jbockerstette** [comment]
There might be many workarounds to my problem, however, the current java
driver does not support doing Document.toJson() when the _id field has the
BinData(4, blahblah...) in it.  As far as I can tell, the getCollection
method just goes and grabs that document and whatever is in it which
includes the _id field. I am not specifically asking for the _id field, it
is just in there as part of the Document that is returned to me. I guess I
could deserialize it by hand one field at a time but that is a pain and not
ideal. There is another more serious problem in that if I want to create a
new document using the java driver, there is no way for me to tell it to
create it with _id : BinData(4, blahblah...). Since jsonapi-store-mongodb
REQUIRES _id = BinData(4, ) or it does not work, that means I can't create
any objects with the java driver and expect them to work with
jsonapi-store-mongodb. In addition, I just think ObjectId is more standard
and more compatible with more things then the BinData(4 style.

I really appreciate you looking into this and I am able to use your
libraries despite this setback.

Document rpps = db.getCollection("rpps").find().first();
String str = rpps.toJson(); //  <-------- Throws exception.

**Comment by pmcnr-hx** [comment]
@jbockerstette this is a tricky one. One of our design decisions is that `jsonapi-server` is store agnostic and therefore we need unique ids that work well across all possible stores. Even if we leave `_id` to be the automatically generated `ObjectId` we'll still need to query by the UUID `id` which is most efficiently stored (and queried) in its binary format. The format in which the UUID is store could be a configuration option of the `jsonapi-store-mongodb`, but implementing that is not currently a priority for us. Would you like to submit a PR for that?

**Comment by jbockerstette** [comment]
Ok, that makes sense. I would like to do a PR but I am still very green
with javascript and nodejs. If I can get something working, I will. Thanks
again.

**Comment by pmcnr-hx** [comment]
No worries. Thanks again for your collaboration.
