### ISSUE TITLE
Example Not working

### ISSUE THREAD

**Issue by stomli** [holidayextras/jsonapi-store-mongodb#37]
I am getting an error on line 8 of the example. Not sure what is going one. 

module.children[2] is undefined at this time so assigning the exports fails. By the end of the code it is no longer undefined. 

I am seem to be missing something in implementing the mongodb store.

Help! :)

**Comment by pmcnr-hx** [comment]
Which version o Node.js are you using @stomli?

**Comment by stomli** [comment]
@pmcnr-hx v6.9.4

**Comment by stomli** [comment]
After a server reboot, I no longer have the undefined issue, now nothing seems to be written to Mongo, but rather still to the memory store.

**Comment by stomli** [comment]
This issue can be closed, ended up being a config issue for me.

**Comment by pmcnr-hx** [comment]
No worries @stomli. Glad you were able to sort it.
